# Generated by Django 5.1.4 on 2024-12-06 19:28

import django.contrib.auth.models
import django.db.models.deletion
import taskApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTasks', models.IntegerField()),
                ('totalAmbassadorsTasks', models.IntegerField()),
                ('totalStudySupportsTasks', models.IntegerField()),
                ('totalProfessionalSupportsTasks', models.IntegerField()),
                ('totalIntermediariesTasks', models.IntegerField()),
                ('totalStudents', models.IntegerField()),
                ('totalAdmins', models.IntegerField()),
                ('totalGuests', models.IntegerField()),
                ('totalAmbassadors', models.IntegerField()),
                ('totalStudySupports', models.IntegerField()),
                ('totalProfessionalSupports', models.IntegerField()),
                ('totalIntermediaries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiativeType', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('initiativePlace', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('studentsName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=20)),
                ('userPermission', models.CharField(max_length=50)),
                ('firstStudentRule', models.CharField(max_length=50, null=True)),
                ('secondStudentRule', models.CharField(max_length=50, null=True)),
                ('adminRule', models.CharField(max_length=50, null=True)),
                ('profileImage', models.ImageField(default='static/Images/defaultUserProfile.png', upload_to='profileImages')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=taskApp.models.taskImageUpload)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskApp.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskApp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskApp.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskApp.userprofile'),
        ),
    ]
