# Generated by Django 5.0.6 on 2024-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='studentEnteredYear',
            field=models.CharField(max_length=50),
        ),
    ]
