# Generated by Django 5.0.6 on 2024-12-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0002_alter_userprofile_studententeredyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='studentEnteredYear',
            new_name='grade',
        ),
    ]
