# Generated by Django 5.1.4 on 2025-04-04 21:10

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0002_alter_superadmin_profileimage_alter_taskimages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rate',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='profileImage',
            field=models.ImageField(default='https://res.cloudinary.com/dkcyr1ca9/image/upload/v1738752231/defaultUserProfile_bqkjax.png', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='taskimages',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(default='https://res.cloudinary.com/dkcyr1ca9/image/upload/v1738752231/defaultUserProfile_bqkjax.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=''),
        ),
    ]
