# Generated by Django 5.1.2 on 2024-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0003_rename_studententeredyear_userprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomments',
            name='publishedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
