# Generated by Django 5.1.4 on 2025-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0003_task_rate_alter_superadmin_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
