# Generated by Django 5.1.4 on 2025-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0004_alter_task_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rate',
            field=models.CharField(default='0'),
        ),
    ]
