# Generated by Django 5.1.2 on 2025-01-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0004_taskcomments_publisheddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='profileImage',
            field=models.ImageField(default='profileImages/defaultAdminProfile.png', upload_to='profileImages'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(default='profileImages/defaultUserProfile.png', null=True, upload_to='profileImages'),
        ),
    ]
