# Generated by Django 5.1.2 on 2025-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0005_superadmin_profileimage_alter_userprofile_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totalTasks',
            field=models.IntegerField(default=0),
        ),
    ]
