# Generated by Django 5.0.6 on 2025-01-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0007_alter_taskcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomments',
            name='superAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskApp.superadmin'),
        ),
        migrations.AlterField(
            model_name='taskcomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskApp.userprofile'),
        ),
    ]
