# Generated by Django 5.0.6 on 2025-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0008_taskcomments_superadmin_alter_taskcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='nationalId',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
