# Generated by Django 5.1.4 on 2025-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0009_superadmin_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='profileImage',
            field=models.ImageField(default='profileImages/defaultUserProfile.png', upload_to='profileImages'),
        ),
    ]
